import random

def getRandomHero():

    allHeroes = [
    "Abathur",
    "Arthas",
    "Diablo",
    "E.T.C",
    "Falstad",
    "Gazlowe",
    "Illidan",
    "Kerrigan",
    "Malfurion",
    "Muradin",
    "Nazeebo",
    "Nova",
    "Raynor",
    "Sgt Hammer",
    "Sonya",
    "Stitches",
    "Tassadar",
    "Tyrael",
    "Tyrande",
    "Uther",
    "Valla",
    "Zeratul",
    "Tychus",
    "Brightwing",
    "Li Li",
    "Murky",
    "Zagara",
    "Rehgar",
    "Chen",
    "Anubarak",
    "Azmodan",
    "Jaina",
    "Thrall",
    "The Lost Vikings",
    "Sylvanas",
    "Kaelthas",
    "Johanna",
    "The Butcher",
    "Leoric",
    "Kharazim",
    "Rexxar",
    "Lt. Morales",
    "Artanis",
    "Lunara",
    "Greymane",
    "Li-Ming",
    "Xul",
    "Dehaka",
    "Tracer",
    "Chromie",
    "Medivh",
    "Guldan",
    "Auriel",
    "Alarak",
    "Zarya",
    "Samuro",
    "Varian",
    "Ragnaros",
    "Zuljin",
    "Valeera",
    "Lucio",
    "Probius",
    "Cassia",
    "Genji",
    "D.Va",
    "Malthael",
    "Stukov",
    "Garrosh",
    "Kelthas",
    "Ana",
    "Junkrat",
    "Alexstrasza",
    "Hanzo",
    "Blaze",
    "Maiev",
    "Fenix",
    "Deckard Cain",
    "Yrel",
    "Whitemane",
    "Mephisto",
    "MalGanis",
    "Orphea",
    "Imperius",
    "Anduin",
    "Qhira",
    "Deathwing",
    "Mei",
    "Hogger"
    ]

    return random.choice(allHeroes)